### ISSUE TITLE
install_windows_package matcher throwing "TypeError: no implicit conversion of nil into String"

### ISSUE THREAD

**Issue by miguelaferreira** [chef-cookbooks/windows#158]
Similarly to what I've reported in #157, I'm tying to use ChefSpec to test a cookbook that uses the windows_package provider.
However, I'm always getting a "TypeError: no implicit conversion of nil into String" exception.

I've created an example cookbook that shows the issue, here https://github.com/miguelaferreira/chefspec_windows_tests

My recipe looks like this:

``` ruby
windows_package '7zip' do
  source 'C:\7z920.msi'
  action :install
end
```

My spec looks like this:

``` ruby
describe 'chefspec_windows_tests::windows_package' do
  let(:chef_run) { ChefSpec::SoloRunner.new(platform: 'windows', version: '2012R2').converge(described_recipe) }

  it 'installs a windows package' do
    expect(chef_run).to install_windows_package('7zip')
  end
end
```

The output of rspec is the follwoing:

``` bash
================================================================================
Recipe Compile Error in /var/folders/sm/tcsqvyfd7hvcw__25f6t7_016l9l6z/T/d20141216-28196-1jayy3w/cookbooks/chefspec_windows_tests/recipes/windows_package.rb
================================================================================

TypeError
---------
no implicit conversion of nil into String

Cookbook Trace:
---------------
  /var/folders/sm/tcsqvyfd7hvcw__25f6t7_016l9l6z/T/d20141216-28196-1jayy3w/cookbooks/chefspec_windows_tests/recipes/windows_package.rb:10:in `from_file'

Relevant File Content:
----------------------
/var/folders/sm/tcsqvyfd7hvcw__25f6t7_016l9l6z/T/d20141216-28196-1jayy3w/cookbooks/chefspec_windows_tests/recipes/windows_package.rb:

  3:  # Recipe:: default
  4:  #
  5:  # Copyright (C) 2014 YOUR_NAME
  6:  #
  7:  # All rights reserved - Do Not Redistribute
  8:  #
  9:  
 10>> windows_package '7zip' do
 11:    source 'C:\7z920.msi'
 12:    action :install
 13:  end
 14:  
 15:  

F

Failures:

  1) chefspec_windows_tests::windows_package installs a windows package
     Failure/Error: let(:chef_run) { ChefSpec::SoloRunner.new(platform: 'windows', version: '2012R2').converge(described_recipe) }
     TypeError:
       no implicit conversion of nil into String
     # /var/folders/sm/tcsqvyfd7hvcw__25f6t7_016l9l6z/T/d20141216-28196-1jayy3w/cookbooks/chefspec_windows_tests/recipes/windows_package.rb:10:in `from_file'
     # ./spec/windows_package_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ./spec/windows_package_spec.rb:8:in `block (2 levels) in <top (required)>'

Finished in 0.76953 seconds (files took 1.91 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/windows_package_spec.rb:7 # chefspec_windows_tests::windows_package installs a windows package
```

As opposed in issue #157, the stack-trace of this issue does not point to the windows cookbook code. It points to my own recipe.

**Comment by dgoradia-atlas** [comment]
I'm getting the same error. Would it be possible to post the hack code you made for @miguelaferreira?
