### ISSUE TITLE
Deprecated feature used, chef_gem compile_time installation

### ISSUE THREAD

**Issue by spuder** [chef-cookbooks/windows#347]
## Version
chef-client 12.8.0 (preview)
Windows 2012 R2

The following errors are encountered

```ruby

Deprecated features used!
  chef_gem[win32-api] chef_gem compile_time installation is deprecated at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:23:in `block in from_file'
  chef_gem[win32-api] Please set `compile_time false` on the resource to use the new behavior. at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:23:in `block in from_file'
  chef_gem[win32-api] or set `compile_time true` on the resource if compile_time behavior is required. at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:23:in `block in from_file'
  chef_gem[win32-service] chef_gem compile_time installation is deprecated at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:23:in `block in from_file'
  chef_gem[win32-service] Please set `compile_time false` on the resource to use the new behavior. at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:23:in `block in from_file'
  chef_gem[win32-service] or set `compile_time true` on the resource if compile_time behavior is required. at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:23:in `block in from_file'
  chef_gem[windows-api] chef_gem compile_time installation is deprecated at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:31:in `block in from_file'
  chef_gem[windows-api] Please set `compile_time false` on the resource to use the new behavior. at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:31:in `block in from_file'
  chef_gem[windows-api] or set `compile_time true` on the resource if compile_time behavior is required. at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:31:in `block in from_file'
  chef_gem[windows-pr] chef_gem compile_time installation is deprecated at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:31:in `block in from_file'
  chef_gem[windows-pr] Please set `compile_time false` on the resource to use the new behavior. at 1 location:

    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:31:in `block in from_file'
  chef_gem[windows-pr] or set `compile_time true` on the resource if compile_time behavior is required. at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:31:in `block in from_file'
  chef_gem[win32-dir] chef_gem compile_time installation is deprecated at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:31:in `block in from_file'
  chef_gem[win32-dir] Please set `compile_time false` on the resource to use the new behavior. at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:31:in `block in from_file'
  chef_gem[win32-dir] or set `compile_time true` on the resource if compile_time behavior is required. at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:31:in `block in from_file'
  chef_gem[win32-event] chef_gem compile_time installation is deprecated at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:31:in `block in from_file'
  chef_gem[win32-event] Please set `compile_time false` on the resource to use the new behavior. at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:31:in `block in from_file'
  chef_gem[win32-event] or set `compile_time true` on the resource if compile_time behavior is required. at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:31:in `block in from_file'
  chef_gem[win32-mutex] chef_gem compile_time installation is deprecated at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:31:in `block in from_file'
  chef_gem[win32-mutex] Please set `compile_time false` on the resource to use the new behavior. at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:31:in `block in from_file'
  chef_gem[win32-mutex] or set `compile_time true` on the resource if compile_time behavior is required. at 1 location:
    - c:/chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:31:in `block in from_file'

Chef Client finished, 17/172 resources updated in 32 seconds
```

**Comment by spuder** [comment]
This is fixed in 1.39.2.
Discovered while creating the issue. Went ahead and created issue anyway incase anyone else runs into this.
