### ISSUE TITLE
cannot load such file -- chef/mixin/powershell_out

### ISSUE THREAD

**Issue by Paxa** [chef-cookbooks/windows#625]
### Cookbook version

7.0

### Chef-client version
12.0.0

### Platform Details
Ubuntu

### Scenario:
We run deployment and `windows` cookbook broke it

```
# cat /var/chef/cache/chef-stacktrace.out
Generated at 2020-03-31 08:14:52 +0000
LoadError: cannot load such file -- chef/mixin/powershell_out
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/chef/cache/cookbooks/windows/libraries/windows_helper.rb:23:in `<top (required)>'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/run_context/cookbook_compiler.rb:191:in `load'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/run_context/cookbook_compiler.rb:191:in `block in load_libraries_from_cookbook'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/run_context/cookbook_compiler.rb:188:in `each'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/run_context/cookbook_compiler.rb:188:in `load_libraries_from_cookbook'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/run_context/cookbook_compiler.rb:99:in `block in compile_libraries'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/run_context/cookbook_compiler.rb:98:in `each'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/run_context/cookbook_compiler.rb:98:in `compile_libraries'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/run_context/cookbook_compiler.rb:71:in `compile'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/run_context.rb:92:in `load'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/client.rb:235:in `setup_run_context'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/client.rb:397:in `run'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/application.rb:261:in `block in fork_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/application.rb:249:in `fork'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/application.rb:249:in `fork_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/application.rb:215:in `block in run_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/application.rb:201:in `run_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/application/client.rb:353:in `block in interval_run_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/application/client.rb:343:in `loop'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/application/client.rb:343:in `interval_run_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/application/client.rb:333:in `run_application'
/var/lib/gems/2.3.0/gems/chef-12.0.0/lib/chef/application.rb:58:in `run'
/var/lib/gems/2.3.0/gems/chef-12.0.0/bin/chef-client:26:in `<top (required)>'
/usr/local/bin/chef-client:23:in `load'
/usr/local/bin/chef-client:23:in `<main>'
```

With pervious release it was working well
I expect it should do nothing when OS is not windows...

**Comment by tas50** [comment]
Version 7.0 of this cookbook requires Chef Infra Client 14.7 or later. Version 12.0.0 was released December 05, 2014 and is no longer supported.
